Repository KIT-Frontend-Team2/Paradise, pull requests merged in 2023-08, with the labels that each got.

#62 🌈feat : Container 반응형 css 추가
  src/components/layout/Container.jsx
Labels: ✨ Feature

#65 🌈feat : 에러바운더리 적용완료
  .env.sample
  src/App.js
  src/apis/HTTPError.js
  src/apis/axiosInstance.js
  src/apis/service/page.api.js
  src/apis/service/user.api.js
  src/apis/service/viewlist.api.js
  src/components/error/Error.jsx
  src/components/error/ErrorBoundary.jsx
  src/components/layout/MainLayout.jsx
  src/components/pages/NotFoundPage.jsx
  src/components/templates/ErrorPageTemplate/ErrorPage.stories.jsx
  src/components/templates/ErrorPageTemplate/ErrorPageTemplate.jsx
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
  src/components/ui/molecules/ProductCard/ProductCard.jsx
  src/consts/ApiKey.js
  src/consts/api.js
  src/hooks/common/useResetError.js
  src/hooks/pageQuery/@config.js
  src/hooks/service/useViewList.service.js
  src/hooks/useMovePage.js
  src/repositories/TokenRepository.js
  src/routes/router.jsx
  src/utils/formatter.js
  src/utils/random-number-maker.js
  src/utils/typeGuard.js
Labels: ✨ Feature, 📚docs, 📝fix, 🔨 Refactor

#69 🌈feat: 채팅 메시지 부분 현재까지의 진행과 카테고리에 맞는 상품 이동 적용
  src/__mock__/apis/chat.api.js
  src/__mock__/datas/chatList.mock.js
  src/__mock__/handler.jsx
  src/atom/chat/atom.js
  src/components/modal/Side/SideBar.jsx
  src/components/modal/chat/Chat.jsx
  src/components/modal/chat/ChatHeader.jsx
  src/components/modal/chat/ChatInput.jsx
  src/components/modal/chat/ChatList.jsx
  src/components/modal/chat/ChatMessage.jsx
  src/components/modal/chat/ChatProductCard.jsx
  src/components/modal/chat/ChatProductCardButton.jsx
  src/components/modal/chat/Chating.jsx
  src/components/ui/organisms/FooterMobile/FooterMobile.jsx
  src/components/ui/organisms/MainFooter/MainFooter.jsx
  src/components/ui/organisms/MainHeader/HeaderCategory.jsx
  src/components/ui/organisms/MainHeader/HeaderChatAlarm.jsx
  src/components/ui/organisms/MainHeader/HeaderScroll.jsx
  src/components/ui/organisms/MainHeader/MainHeader.jsx
  src/components/ui/organisms/MainHeader/UserInfo.jsx
Labels: ✨ Feature, 📝fix

#72 🌈feat : 로그인, 로그아웃, 회원가입 기능 추가
  src/apis/service/user.api.js
  src/atom/header/atom.js
  src/components/modal/Side/SideBar.jsx
  src/components/pages/AuthPage.jsx
  src/components/pages/LandingPage.jsx
  src/components/templates/AuthPageTemplate/LoginTemplate.jsx
  src/components/templates/AuthPageTemplate/SignUpTemplate.jsx
  src/components/templates/AuthPageTemplate/validation.js
  src/components/ui/organisms/MainHeader/UserInfo.jsx
  src/hooks/service/user.service.js
  src/repositories/UserRepository.js
  src/routes/router.jsx
Labels: ✨ Feature, 💄style

#78 🌈feat: 헤더 카테고리, 마이페이지 이동
  src/apis/service/chat.api.js
  src/components/modal/chat/Chat.jsx
  src/components/modal/chat/ChatList.jsx
  src/components/modal/chat/ChatMessage.jsx
  src/components/modal/chat/ChatProductCard.jsx
  src/components/modal/chat/Chating.jsx
  src/components/ui/organisms/MainHeader/HeaderCategory.jsx
  src/components/ui/organisms/MainHeader/HeaderScroll.jsx
  src/components/ui/organisms/MainHeader/MainHeader.jsx
  src/components/ui/organisms/MainHeader/UserInfo.jsx
  src/hooks/service/useChat.service.js
Labels: ✨ Feature

#81 🚧refactor : ProductListTemplate로 상품 리스트 통합
  src/components/pages/ProductListPage.jsx
  src/components/pages/ProductSearchPage.jsx
  src/components/pages/ProductUserListPage.jsx
  src/components/templates/ProductListTemplate/ProductListTemplate.jsx
  src/components/templates/ProductSearchTemplate/ProductSearchTemplate.jsx
  src/components/templates/ProductSearchUserTemplate/ProductSearchUserTemplate.jsx
Labels: 🔨 Refactor

#83 Update README.md
  README.md
Labels: 🚀chore

#86 📝fix : 헤더 카테고리에 ,가 하나 더 들어가있어서 카테고리 배열에 empty값이 들어가는 현상 수정
  src/components/ui/organisms/MainHeader/HeaderCategory.jsx
Labels: 📝fix

#85 🌈feat : 물품 등록, 수정 api 연결
  src/apis/service/product.api.js
  src/components/pages/ProductUpdatePage.jsx
  src/components/templates/ProductFormTemplate/ProductForm.jsx
  src/components/ui/molecules/Map/ProductFormMap.jsx
  src/components/ui/organisms/DeFormImagePreviewGroup/DeFormImagePreviewGroup.jsx
  src/components/ui/organisms/DeFormTagGroup/DeFormTagGroup.jsx
Labels: ✨ Feature

#87 🚀chore : 클래스 구문 사용을 위한 babel.config 추가
  babel.config.json
  package-lock.json
  package.json
Labels: 🚀chore

#94 🌈feat : 찜버튼 mui 아이콘 효과 추가
  src/components/ui/atoms/Button/WishButton.jsx
Labels: ✨ Feature

#95 🌈feat : 푸터 스타일 변경
  src/components/ui/organisms/MainFooter/MainFooter.jsx
Labels: ✨ Feature

#93 🌈feat : 물품 등록 페이지 반응형 css 추가
  src/components/templates/ProductFormTemplate/ProductForm.jsx
  src/components/templates/ProductFormTemplate/style.js
  src/components/ui/organisms/DeFormImagePreviewGroup/DeFormImagePreviewGroup.jsx
  src/utils/formatter.js
Labels: ✨ Feature, 🔨 Refactor

#92 🌈feat : 쿠키를 이용한 아이디 기억하기 기능 추가
  public/favicon.ico
  public/index.html
  src/apis/service/user.api.js
  src/atom/header/atom.js
  src/components/layout/MainLayout.jsx
  src/components/templates/AuthPageTemplate/LoginTemplate.jsx
  src/components/templates/AuthPageTemplate/validation.js
  src/components/templates/MainPageTemplate/MainPageTemplate.jsx
  src/components/templates/MyPageTemplate/MyContent.jsx
  src/components/templates/MyPageTemplate/MyReviewTemplate.jsx
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
  src/components/ui/molecules/ProductCard/ProductCard.jsx
  src/components/ui/molecules/ReviewCard/ReviewCard.jsx
  src/components/ui/molecules/ReviewCard/ReviewCard.stories.jsx
  src/components/ui/molecules/SlideBanner/SSlideBanner.jsx
  src/components/ui/organisms/DeImgSection/DeImgSection.jsx
  src/components/ui/organisms/DeProductCategoryTag/DeProductCategoryTag.jsx
  src/components/ui/organisms/DeProductSection/DeProductSection.jsx
  src/components/ui/organisms/MainHeader/UserInfo.jsx
  src/components/ui/organisms/MyMenu/MyMenu.jsx
  src/components/ui/organisms/ReviewProducts/ReviewIsNullCard.jsx
  src/components/ui/organisms/ReviewProducts/ReviewIsNullProducts.jsx
  src/components/ui/organisms/ReviewProducts/ReviewProducts.jsx
  src/hooks/service/review.service.js
  src/hooks/service/user.service.js
  src/repositories/AuthCookie.js
  src/repositories/UserRepository.js
  src/routes/private.jsx
Labels: ✨ Feature

#98 📝fix : 드래그앤드롭에서 alert메세지 뜨고 사이트 멈추는 현상 수정
  src/components/ui/organisms/DeFormImagePreviewGroup/DeFormImagePreviewGroup.jsx
Labels: 📝fix

#88 🌈feat : 마이페이지 api 연결
  src/__mock__/apis/authPage.api.js
  src/__mock__/datas/userSignup.mock.js
  src/__mock__/datas/userlogin.mock.js
  src/__mock__/handler.jsx
  src/apis/service/user.api.js
  src/components/pages/MyPage.jsx
  src/components/templates/AuthPageTemplate/validation.js
  src/components/templates/MyPageTemplate/MyCashTemplate.jsx
  src/components/templates/MyPageTemplate/MyProfileTemplate.jsx
  src/components/templates/MyPageTemplate/MyRecentTemplate.jsx
  src/components/templates/MyPageTemplate/MySellTemplate.jsx
  src/components/templates/MyPageTemplate/MyWishTemplate.jsx
  src/components/ui/organisms/MyHeader/MyHeader.jsx
  src/components/ui/organisms/MyMenu/MyMenu.jsx
  src/components/ui/organisms/MyPageSection/MyChangePw.jsx
  src/components/ui/organisms/MyPageSection/MyPageContent.jsx
  src/components/ui/organisms/MyPageSection/MyPageInfo.jsx
  src/components/ui/organisms/MyPageSection/MyUploadCard.jsx
  src/components/ui/organisms/MyPageSection/SellMenuBar.jsx
  src/hooks/service/useMypage.service.js
  src/utils/calendar.js
Labels: ✨ Feature

#99 🌈feat : 리뷰작성 기능 추가
  src/apis/service/review.api.js
  src/components/modal/Review/Review.jsx
  src/components/modal/Review/ReviewDetail.jsx
  src/components/modal/Review/validator.js
  src/components/templates/MyPageTemplate/MyContent.jsx
  src/components/templates/MyPageTemplate/MyReviewTemplate.jsx
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
  src/components/ui/molecules/ReviewCard/ReviewCard.jsx
  src/components/ui/molecules/ReviewCard/ReviewCard.stories.jsx
  src/components/ui/organisms/ReviewProducts/ReviewIsNullCard.jsx
  src/components/ui/organisms/ReviewProducts/ReviewIsNullProducts.jsx
  src/components/ui/organisms/ReviewProducts/ReviewProducts.jsx
  src/consts/product.js
  src/hooks/service/review.service.js
Labels: ✨ Feature

#101 🌈feat : toast message 추가
  package-lock.json
  package.json
  src/components/layout/MainLayout.jsx
  src/components/modal/Review/Review.jsx
  src/components/templates/MyPageTemplate/MyReviewTemplate.jsx
  src/consts/message.js
  src/hooks/service/review.service.js
  src/utils/toast-message.js
Labels: ✨ Feature

#103 💄style : 코드 포맷팅 누락
  src/apis/service/product.api.js
  src/components/layout/MainLayout.jsx
  src/components/modal/Review/Review.jsx
  src/components/templates/MyPageTemplate/MyReviewTemplate.jsx
  src/components/ui/molecules/ProductCard/ProductCard.jsx
  src/components/ui/organisms/DeImgSection/DeImgSection.jsx
Labels: 💄style

#104 🌈feat : 물품 등록 시 배경 제거 기능 추가
  package-lock.json
  package.json
  src/components/modal/Review/Review.jsx
  src/components/pages/ProductRegisterPage.jsx
  src/components/templates/ProductFormTemplate/ProductForm.jsx
  src/components/templates/ProductFormTemplate/style.js
  src/components/ui/organisms/DeFormImagePreviewGroup/DeFormImagePreviewGroup.jsx
  src/components/ui/organisms/MainFooter/MainFooter.jsx
Labels: ✨ Feature, 📝fix, 🔨 Refactor

#106 💄style : 디테일 페이지 css 변경
  src/components/ui/organisms/DeImgSection/DeImgSection.jsx
  src/hooks/service/useViewList.service.js
Labels: 💄style

#108 🌈feat: 배포 페이지 에러 해결을 위한 채팅 목록 머지
  package-lock.json
  package.json
  src/App.js
  src/atom/chat/atom.js
  src/components/modal/chat/Chat.jsx
  src/components/modal/chat/ChatInput.jsx
  src/components/modal/chat/ChatMessage.jsx
  src/components/modal/chat/Chating.jsx
  src/components/templates/AuthPageTemplate/LoginTemplate.jsx
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
  src/components/ui/organisms/DeProductSection/DeProductSection.jsx
  src/components/ui/organisms/MainHeader/HeaderCategory.jsx
  src/components/ui/organisms/MainHeader/HeaderChatAlarm.jsx
  src/components/ui/organisms/MainHeader/HeaderSearch.jsx
  src/components/ui/organisms/MainHeader/MainHeader.jsx
  src/components/ui/organisms/MainHeader/UserInfo.jsx
  src/hooks/service/useChat.service.js
  src/hooks/service/user.service.js
  src/socket/socket.js
Labels: ✨ Feature, 📝fix

#107 🌈feat : 검색시 해당 키워드 보여주기 추가
  src/components/templates/ProductListTemplate/ProductListTemplate.jsx
  src/components/ui/organisms/MaLineBanner/MaLineBanner.jsx
Labels: ✨ Feature

#112 🌈feat : 쿠키를 통한 로그인 유효성검사 추가
  src/atom/header/atom.js
  src/components/templates/AuthPageTemplate/LoginTemplate.jsx
  src/hooks/service/user.service.js
  src/repositories/LoginCookie.js
  src/routes/private.jsx
Labels: ✨ Feature

#117 🌈feat : review 페이지 분리 통합
  src/components/templates/MyPageTemplate/MyReviewTemplate.jsx
  src/components/ui/molecules/ReviewCard/ReviewCard.jsx
  src/components/ui/organisms/ReviewProducts/ReviewIsNullCard.jsx
  src/components/ui/organisms/ReviewProducts/ReviewIsNullProducts.jsx
  src/components/ui/organisms/ReviewProducts/ReviewProducts.jsx
Labels: 🔨 Refactor

#120 💄style : 채팅창 css 수정
  src/components/modal/Side/SideBar.jsx
  src/components/modal/chat/Chat.jsx
  src/components/modal/chat/ChatHeader.jsx
  src/components/modal/chat/ChatInput.jsx
  src/components/modal/chat/ChatMessage.jsx
  src/components/modal/chat/ChatProductCard.jsx
  src/components/modal/chat/Chating.jsx
  src/components/ui/organisms/HeaderMobile/HeaderMobile.jsx
Labels: 💄style

#122 Feature/chat list
  src/components/modal/chat/Chating.jsx
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
  src/components/ui/organisms/DeProductSection/DeProductSection.jsx
  src/components/ui/organisms/MainHeader/HeaderCategory.jsx
  src/components/ui/organisms/MainHeader/UserInfo.jsx
  src/hooks/service/useChat.service.js
Labels: ✨ Feature

#123 🌈feat : 헤더, 푸터 css 수정 및 반응형 css 추가
  src/assets/images/headerlogo.png
  src/atom/chat/atom.js
  src/components/layout/Container.jsx
  src/components/layout/MainLayout.jsx
  src/components/modal/chat/Chat.jsx
  src/components/modal/chat/ChatHeader.jsx
  src/components/pages/MyPage.jsx
  src/components/templates/MyPageTemplate/MyReviewTemplate.jsx
  src/components/templates/ProductFormTemplate/style.js
  src/components/ui/organisms/FooterMobile/FooterMobile.jsx
  src/components/ui/organisms/HeaderMobile/HeaderMobile.jsx
  src/components/ui/organisms/MainFooter/MainFooter.jsx
  src/components/ui/organisms/MainHeader/HeaderCategory.jsx
  src/components/ui/organisms/MainHeader/HeaderScroll.jsx
  src/components/ui/organisms/MainHeader/HeaderSearch.jsx
  src/components/ui/organisms/MainHeader/MainHeader.jsx
  src/components/ui/organisms/MainHeader/UserInfo.jsx
Labels: ✨ Feature

#118 🌈feat : 임시 데이터 추가
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
  src/components/ui/molecules/DeProductTitle/DeProductTitle.jsx
  src/components/ui/molecules/DeUserCard/DeUserCard.jsx
  src/components/ui/molecules/ProductCard/ProductCard.jsx
  src/components/ui/molecules/ReviewCard/ReviewCard.jsx
  src/components/ui/organisms/DeUserProductSection/DeUserProductSection.jsx
  src/components/ui/organisms/MaSection/MaSection.jsx
  src/components/ui/organisms/ProductList/ProductList.jsx
  src/components/ui/organisms/ReviewProducts/ReviewIsNullCard.jsx
Labels: ✨ Feature

#125 📝fix : 물품 등록 오류 시 try catch문 추가
  src/components/templates/ProductFormTemplate/ProductForm.jsx
  src/components/templates/ProductFormTemplate/validator.js
Labels: 📝fix

#127 🌈feat : 디테일 페이지 임시수정
  src/__mock__/datas/detailPage.mock.js
  src/assets/images/mobileLogo.jpg
  src/components/templates/AuthPageTemplate/validation.js
  src/components/templates/MainPageTemplate/MainPageTemplate.jsx
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
  src/components/ui/molecules/DeUserProductButton/DeUserProductButton.jsx
  src/components/ui/molecules/ProductCard/ProductCard.jsx
  src/components/ui/molecules/SProductCarousel/SProductCarousel.jsx
Labels: 🔨 Refactor, 🚜test

#129 📝fix : 마이페이지 css 수정
  src/components/templates/MyPageTemplate/MyCashTemplate.jsx
  src/components/templates/MyPageTemplate/MyContent.jsx
  src/components/templates/MyPageTemplate/MySellTemplate.jsx
  src/components/templates/MyPageTemplate/MyWishTemplate.jsx
  src/components/ui/organisms/MyPageSection/MyUploadCard.jsx
  src/components/ui/organisms/MyPageSection/SellMenuBar.jsx
Labels: 📝fix

#135 🚜test : 테스트 코드, 리펙토링 테스트 코드 추가
  src/__mock__/datas/detailPage.mock.js
  src/components/templates/AuthPageTemplate/validation.js
Labels: 🚜test

#138 📚docs : cacheTime 수정
  src/hooks/pageQuery/@config.js
Labels: 📚docs

#140 📝fix : 회원가입 버그 수정
  src/components/templates/AuthPageTemplate/LoginTemplate.jsx
  src/components/templates/AuthPageTemplate/validation.js
  src/components/ui/organisms/MyMenu/MyMenu.jsx
  src/hooks/pageQuery/@config.js
Labels: 📝fix
